# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da4c9c74ece0681ea3cca6a3cfd4e615c988fb36a9f2c8117c7baae5ccd0326af4c4554810ca11bb70b9d209a913955cfca4269823f97515156247fd29ef4b9f

test:
  secret_key_base: 8b099e2ddf563606cfa4048aaa1919579b8707819859018107534311fbdfef7fd06abdcb3833f19c3c759042b8bd0ea82bfc62d48e76950e915c21de804de92c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
